### PR TITLE
Fix the Code Formatting workflow

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @davidanthoff

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Bump @mcmcgrath13

**Comment by mcmcgrath13** [comment]
> Bump @mcmcgrath13

I'm not a maintainer here, just a friend of the package 🤩

**Comment by DilumAluthge** [comment]
Bump @davidanthoff

**Comment by DilumAluthge** [comment]
Bump @davidanthoff 

@mcmcgrath13 Do you know who any of the other committers are?

**Comment by mcmcgrath13** [comment]
@davidanthoff tends to go through and merge several PRs at once.  Is this urgent?

@jeremiahpslewis might have more info.

**Comment by davidanthoff** [comment]
This has to flow in via an update in PkgButlerEngine.jl, the file edited in this PR here is under the control of the package butler. I've pushed an update to PkgButlerEngine, but want to test that for a while before I make it widely available, so will probably take a few days until it all flows into this repo here.

**Pull request closed without merging**
