### PR TITLE
Pluto Support

### PR DESCRIPTION
**Pull request by mcmcgrath13**
Hey @davidanthoff ! 

I'm working on adding vega/vega lite support to pluto and they recommended we add either a `text/html` or `application/vnd.pluto.html+xml` mime type.  Either will be treated the same on the pluto side, it's more of a question of is it okay to use the `script` tags in a generic `text/html` mime type (have you seen issues with this in the past?).

The current iteration uses `text/html`, but I can swap that out for the pluto-specific mime if you prefer.  I think they need to create that mime on the pluto side, but it seems like that's a light lift.

https://github.com/fonsp/Pluto.jl/pull/253

### CODE REVIEW

**Comment by fonsp** [comment]
@mcmcgrath13 Did you test my suggested code? I'm only trying it out now.

**Comment by mcmcgrath13** [comment]
Yup! I had to tweak it a bit, but I got it working with the current master branch.

**Comment by fonsp** [comment]
https://github.com/mcmcgrath13/VegaLite.jl/pull/1

**Comment by davidanthoff** [comment]
Cool!

I think we can't do the `text/html` MIME type because we can't really assume that all consumers of that MIME type will run script blocks, so I think if we were to go with this strategy here, we should use the pluto specific MIME type.

The integration story with other clients we have so far is very different: Jupyterlab, nteract, VS Code and ElectronDisplay.jl all can just natively handle the vega and vega-lite MIME types. In that design, we don't have any front-end specific code here in VegaLite.jl. I think at some level that is the right design: I wouldn't want to add support for a MIME type for each front end. It also strikes me as much robust to have the _interface_ here based on a declarative format like vega and vega-lite specs than to ship around code snippets that might or might not work (for example the implementation here makes certain assumptions how javascript can be loaded etc that might not always hold, and it seems better to me to make those kinds of choices in the front-end itself. For example, the code here will only work while online. What if Pluto wanted to add support for working in an offline scenario where no internet connection is available?).

Having said that, there are also downsides  to shipping the client side javascript with the clients. The main one is probably updating. vega and vega-lite have relatively frequent releases. In the VS Code extension we solved this problem: we ship a new version of the extension every couple of days in any case, and we have scripts that automatically make sure we always ship the latest versions of vega and vega-lite. That has really worked out well. The story on the Jupyterlab side is very different: they ship like every 6 months or so, so if you miss one of these ship windows, you are stuck with an old version of vega or vega-lite.

BUT, I'd be happy to merge this for now if you all feel this is the way to go.

**Comment by mcmcgrath13** [comment]
I can argue it both ways.

One of the things I like about VegaLite.jl declaring which versions it's working with is that means the VegaLite.jl version is the only thing that dictates the output in Pluto (I ran into a frustrating issue back in the day where IJulia/JupyterLab had an older version of Vega supported and my plot wasn't interactive and I had to go down a real rabbit hole to figure out why).  However, this means that Pluto.jl is now guaranteeing that the frontend (for `<script>` tags) is stable, that the internet is available, and that it will maintain up to date version info for vega, vega lite, and vega embed.

Would Pluto.jl be able to use directly the vega/lite artifacts? What would that look like?

**Comment by fonsp** [comment]
I’ll comment more later, but Pluto uses a service worker to cache all CDN assets, including the vega scripts, so that they work offline.

**Comment by fonsp** [comment]
Hi David, thanks for your input.

This comment is a bit subjective, apologies, but I have a more concrete suggestion at the end.

I think that Julia's MIME system is an amazing feature, because it means that mutually unaware packages can support each other, in a forwards-backwards compatible way. Without these common specs (like `text/html`), every combination of visualisation+frontend packages would need manual support.

I think everyone implementing the `text/html` spec (and others) is a big win. It makes it much easier to create a new frontend, or a new interactive visualisation. But like you mentioned, there are frontends that don't execute script tags (ie implement the spec only partially), perhaps for good reason. For those frontends, a workaround is appropriate. 

In the case of vega/vegalite, having a well-defined spec is actually part of the project, so my praise for `text/html` should also apply to `application/vnd.vegalite.v4+json`. Since it is a major plotting package (and one that I like), adding vega-specific functionality to Pluto might not be as undesirable as I initially thought.

But I still have my concerns about versioning the JS dependencies. The MIME type includes the major version, which solves most of my concerns, but:
- a frontend will need to support all major versions forever.
- minor and patch releases _can_ change the result of a plot. To prevent it, you would need to 
Both of these concerns are minor, but they are relevant for a scientific language. These problems don't exist if the JS dependencies and VegaLite.jl are versioned together, like they would be in this PR. (And `text/html` is backwards compatible.)

## Pluto MIME?
I agree that this package should not have Pluto-specific code - a Pluto MIME is not nice. I guess my suggestion was to support a MIME type `text/html.that.executes.script.tags.like.a.browser`. 

But maybe this isn't necessary: PlotlyJS.jl is in a similar situation (JS dependencies for plotting). Like VegaLite.jl, they implement a Vega/Plotly specific MIME type: ([VegaLite](https://github.com/queryverse/VegaLite.jl/blob/master/src/rendering/show.jl#L53-L60), [PlotlyJS](https://github.com/JuliaPlots/PlotlyJS.jl/blob/master/src/display.jl#L393-L397)) and an unfortunate Juno-specific MIME ([VegaLite](https://github.com/queryverse/VegaLite.jl/blob/master/src/rendering/show.jl#L122-L124), [PlotlyJS](https://github.com/JuliaPlots/PlotlyJS.jl/blob/master/src/display.jl#L17)) to support frontends with static HTML renderers, but they also implement the `text/html` MIME: ([PlotlyJS](https://github.com/JuliaPlots/PlotlyJS.jl/blob/master/src/display.jl#L16)), which renders a `<script>` with the dependency as `src`.

This works, because all frontends that support plotly through the plotly MIME (because they do not support `<script>`) prioritize the plotly MIME over the `text/plain` MIME. 

I think that this would also work for VegaLite! It looks like the vega-specific MIMEs are prioritized over `text/plain` in:
- VS Code: [display.jl](https://github.com/julia-vscode/julia-vscode/blob/33e493ebea540bb54d87737622590336cdfd97bd/scripts/packages/VSCodeServer/src/display.jl#L96-L108)
- IJulia: [display.jl](https://github.com/JuliaLang/IJulia.jl/blob/0ac5483b3d501802dea277b25164558696939bab/src/display.jl#L37-L41) I don't fully understand Jupyter's display, but at least the vega MIMEs and the Plotly MIME are treated equally, so if it works for Plotly then it should work for vega
- Juno: VegaLite.jl has a [Juno-specific show method](https://github.com/queryverse/VegaLite.jl/blob/master/src/rendering/show.jl#L122-L124), just like Plotly.

**Comment by mcmcgrath13** [comment]
@fonsp just to summarize, are you suggesting that:  VegaLite.jl implement the `text/html` mime as this PR does? (and asserting that this shouldn't break any existing displays as they all prioritize the vendor specific tags over `text/html`?)

**Comment by fonsp** [comment]
Yes :)

**Comment by fonsp** [comment]
Summary is that I think `text/html` will not break support for any IDE that currently supports vega, and add support for Pluto, Franklin, maybe more.

If you are not against using `text/html`, I can test it out on the different IDEs.

**Comment by juliohm** [comment]
I'd love to be able to use VegaLite.jl + Pluto.jl with my students. I see that this discussion got stuck. Is there anything planned for the near future that would solve this current limitation in interoperability?

**Comment by davidanthoff** [comment]
I believe the classic Jupyter notebook interface does not have support for the vega and vega-lite mime types, and would end up getting the `text/html` version, which was one of the main (if not the primary) reason to not add `text/html` support here. In general, for Jupyter there are many client implementations, and we can't assume that they all support the `vega` and `vega-lite` MIME types, in fact many don't. In those cases it is quite crucial that they fall back onto the PNG MIME type, and I don't think we can accomplish that if we include support for the `text/html` MIME type.

I don't have much time until next year to look into any of this. I think the only thing we could do in the short term is to come up with our own MIME type and merge that quickly: if it was a Pluto specific MIME type, there would be no risk that we break anything else by adding that, so I'd be ok to merge that quickly. I think anything else would the earliest happen once I have more time in the spring.

If someone does that, please make sure to ping me on Slack, at the moment I've given up on keeping track with my github notifications :)

**Comment by fonsp** [comment]
> I believe the classic Jupyter notebook interface does not have support for the vega and vega-lite mime types

I see! Because on classic Jupyter, you want the fallback to `text/plain` to be triggered, to open the external viewer.

Let me think this over, I will send you a message when it's ready

**Comment by davidanthoff** [comment]
No, I want to fall back to PNG on classic Jupyter notebook, not `text/plain`. That way a plot at least shows always, just might not have interactivity.

**Comment by mcmcgrath13** [comment]
@fonsp @davidanthoff bringing this PR back to life - is this the correct to do list at this point?

- [ ] Update this PR to use the latest vegalite.jl code
- [ ] Change the PR to use the `application/vnd.pluto.html+xml` mime type (@fonsp does this exist & is this correct?)
- [ ] (Maybe) update Pluto with the mime type set up here

**Comment by davidanthoff** [comment]
Yes, that sounds good to me. And probably also update Vega.jl in the same way, right?

**Comment by mcmcgrath13** [comment]
> Yes, that sounds good to me. And probably also update Vega.jl in the same way, right?

Seems reasonable to me!

**Comment by fonsp** [comment]
@mcmcgrath13 the `application/vnd.pluto.html+xml` does not exist, and I don't want to add it, I think the `text/html` MIME type makes sense. This would also add support for Franklin.jl and Documenter.jl without [compatibility code](https://github.com/queryverse/VegaLite.jl/blob/7b81cc6ad2bbc15b7635fe53319ed8de29c7a002/docs/make.jl#L3).

I actually suspect that the html show method also works on classic Jupyter, since they display with iframe (maybe we can test that) but to be really safe you could add this to only enable the new html MIME for Pluto:

```julia
Base.showable(m::MIME"text/html", v::VLSpec) = isdefined(Main, :PlutoRunner)
```

(This is the officially supported way to check if you are running in a Pluto notebook process).

**Comment by davidanthoff** [comment]
As I explained above we can't just add `text/html` support generally, that would break too many existing scenarios. I'd be fine with the runtime check for `PlutoRunner`.

**Comment by mcmcgrath13** [comment]
Update checklist

 * [ ]  Update this PR to use the latest vegalite.jl code
 * [ ]  Add the showable check for pluto runner
 * [ ]  Make same updates at Vega.jl

**Comment by mcmcgrath13** [comment]
See #401 for the updated PR (this one is broken)

**Pull request closed without merging**
