### PR TITLE
Add support for multi-data tooltips

### PR DESCRIPTION
**Pull request by noahrhodes**
Setting tooltips for multiple components was not working (see #332)

`augument_encoding_type` did not run correctly for an array that was passed in as the tooltip information.

this change adds `augment_encoding_type(x::Array, data::Vega.DataValuesNode)` for array types.  It takes arrays and runs `augment_encoding_type` on the internal components

This code snippet now works:
```Julia
using VegaLite, VegaDatasets

iris = dataset("iris")|>
@vlplot(
    tooltip=[{field="species"},{field="sepalLength"}],
    data=iris,
    :point,
    x=:petalWidth,
    y=:petalLength,
    color=:species,
)
```

There is a line in the `docs/src/examples/examples_table_based_plots.md`     that can be updated if this change is added      `#tooltip=[{field="Origin",type="nominal"},{field="Cylinders",type="quantitative"}]  #array not supported`

This is my first contribution to the package.  Is there anything else I should add to this pull request?
This fixes the problem and passes the tests, but I am unsure if there are other implications.  This may not even be the correct way to fix this problem, and I am happy to take pointers to a different approach.

### CODE REVIEW

**Review by davidanthoff — CHANGES_REQUESTED** [review]
Awesome, that does look correct to me!

Could you maybe add a test that exercises this new code path?

I think eventually we would probably also want a simple `=[:foo, :bar]` to work, but we can do that in a follow-up PR.

**Comment by noahrhodes** [comment]
Changes made:
- Removed println statements
- Changed ::Array to ::AbstractArray
- Added a test for the code path
- Updated[ docs example](https://www.queryverse.org/VegaLite.jl/stable/examples/examples_table_based_plots/#Mosaic-Chart-with-Labels-1) to use array instead of a calculation for hover text

As for the test, I wasn't sure what to really test, or where to put it.  I added a test that ran a @vlplot macro with tooltip array, and checked that the tooltip encoding is an array.  

> I think eventually we would probably also want a simple =[:foo, :bar] to work, but we can do that in a follow-up PR.

It works just fine as is!

Let me know if there are any further changes to be made!

**Comment by noahrhodes** [comment]
Would it be possible to review and merge this sometime in the near future? It obviously hasn't been urgent, but a new issue was created about (#415) multiple field tool-tips.

**Comment by rtedwards** [comment]
Bump on this PR.  Would love to see this merged.  @noahrhodes @davidanthoff

**Pull request merged**
