### PR TITLE
bump version of JSONSchema

### PR DESCRIPTION
**Pull request by montyvesselinov**

### CODE REVIEW

**Comment by montyvesselinov** [comment]
[no_block]

can you please bump the JSONSchema version because creates a conflict in a package that uses VegaLite?

Thank you very much!

**Comment by montyvesselinov** [comment]
@davidanthoff merging this PR will be great! Thank you very much!

**Comment by odow** [comment]
This is causing issues for JuMP, because we use JSONSchema 0.3: https://discourse.julialang.org/t/problems-to-build-cplex/53671

However, it doesn't look like you are actually validating user-JSON based on a schema? It just looks like you're reading a JSON file, and then accessing the `.data` field of the schema. 
https://github.com/queryverse/VegaLite.jl/blob/f3daf2e0e1e63b8bb6e8fdab195a8bae2ced6947/src/VegaLite.jl#L31

https://github.com/queryverse/VegaLite.jl/blob/f3daf2e0e1e63b8bb6e8fdab195a8bae2ced6947/src/dsl_vlplot_function/dsl_vlplot_function.jl#L119

https://github.com/queryverse/VegaLite.jl/blob/f3daf2e0e1e63b8bb6e8fdab195a8bae2ced6947/src/dsl_vlplot_function/shorthandparser.jl#L40-L55

JSONSchema can probably be replaced with just JSON.jl. Another sign you aren't actually validating anything is that the tests still pass despite breaking changes JSONSchema. I'll make a new PR.

**Comment by davidanthoff** [comment]
Closing, and going with https://github.com/queryverse/VegaLite.jl/pull/352 instead.

**Pull request closed without merging**
