### PR TITLE
Include link to free PDF

### PR DESCRIPTION
**Pull request by rick2047**
I was reading the docs on my personal laptop and the IEEE paywall hit me pretty hard. The PDF added is a preprint but I guess it will have the same content.

### CODE REVIEW

**Comment by davidanthoff** [comment]
@domoritz, is that preprint link there a good idea?

@rick2047, could you maybe label that link as "preprint", to make it clear that the link goes to a different content than the "real" DOI link.

**Comment by domoritz** [comment]
Yes, the link is good and the document should be persistent. The PDFs are almost identical (uploaded after publication) so you can but don't need to say that it's not the official copy if you don't want to.

**Comment by rick2047** [comment]
I have marked the pre print as such. Can we merge this now?

**Comment by davidanthoff** [comment]
Thanks!

**Pull request merged**
