### PR TITLE
Add more vega APIs

### PR DESCRIPTION
**Pull request by davidanthoff**
This adds `@vgplot`, `@vgfrag`, `vgplot` and `vgfrag`. They work exactly like their vega-lite counterparts.

This PR also changes (again) how data is handled. It is now stored as columns, right until we serialize as JSON. I have one more step on that part that will hopefully (in some scenarios) allow us to really minimize the copying of data we need to do.

I also added some code that output a vega-lite and vega spec as Julia code that uses the `@vlplot` and `@vgplot` command. @tkf, right now we seem to have a `Base.show` method that prints julia code when certain context things are set. I think you added that. Is that the official Julia way to do this? As a user, is there some simple way for me to take `x` and say "give me a julia code representation of that?". The goal of all of this is that we can convert the vega examples super quickly, I really want us to get to a point where we can do `load("foo.vega") |> save("foo.jl")`.

And I fixed a completely unrelated bug because I discovered it :)

### CODE REVIEW

**Comment by tkf** [comment]
> right now we seem to have a `Base.show` method that prints julia code when certain context things are set. I think you added that. Is that the official Julia way to do this?

Yes, I added it in #162.  Sadly, there is no official way to do this: https://github.com/JuliaLang/julia/issues/33260

**Comment by tkf** [comment]
BTW, IIRC, using `:compact` for this was a super dirty hack to avoid super lengthy output from `[spec1, spec2, spec3]` in REPL.

**Comment by davidanthoff** [comment]
Ok, I've slightly changed the way to detect the situation when we are printed as part of a container, I think for now that is hopefully good enough.

**Comment by tkf** [comment]
What happens if you hit `@info "message" x` and `x` is happened to be a vega-lite spec? Doesn't it print everything including the data array?

Also, `get(io, :typeinfo, Nothing)` relies on that _every container implementer_ knew about `:typeinfo` and use it appropriately.  I think this is too optimistic.  For example,  [`display(Dict(:a=>T()))` didn't set `:typeinfo`  last time I checked](https://discourse.julialang.org/t/how-to-detect-in-show-that-you-are-computing-display-for-the-repl/18951/27).

If you want "real" `repr` for potentially large output via `show(::IO, spec)` or `show(::IO, ::MIME"text/plain", spec)`, I think it is best to make it hard to hit that path for now.  If your end-goal is a nice FileIO.jl integration, I think it might be the best approach to start using `MIME"application/julia"` as no one is using it ATM.

**Comment by davidanthoff** [comment]
Agreed on all counts.

So for now I've made 2-arg `show` show a one-line version of the code, based on the same logic that we had previously. I now don't include the data, that is a change to the previous implementation. Instead I emit `data=...`. That makes the output non-evaluable, but maybe that is ok for now.

I also added the `text/plain` MIME type to output a multi-line version, which I think is how it is supposed to be? Also doesn't include data, but the `data=...` stub.

And then one can use `printrepr` if one wants to get full evaluable code.

And for `save`/`load` I'll follow your suggestion with the julia MIME type.

Do you think this is roughly ok now? I'm going to merge, but would still be interested in feedback and potential follow-up changes, you have a much better understanding here than I do :)

**Pull request merged**
