### PR TITLE
Pluto support

### PR DESCRIPTION
**Pull request by mcmcgrath13**
I accidentally changed the base on #324 when trying to fix something else and the PR was closed.  Here is the updated code.

I am populating the scripts with the minified JS from the artifacts - is this the best way to go? @davidanthoff do you want to use the sourceMap-less artifacts with the full html as well? (prevents a console warning)

### CODE REVIEW

**Comment by davidanthoff** [comment]
I think this looks good, as long as it is ok that every plot in a notebook will now include the entire vega and vega-lite codebase again and again, right? At least for Jupyter notebooks I thought that was not really an option, given that these outputs are stored in the files... But I think that is really something that @fonsp needs to decide whether he thinks that is a good solution for Pluto or not. The benefit of this of course is that it should work offline.

Not sure about the existing full html case, where does that console warning show up? So far I always had the impression that is pretty much just works?

Ping me once you are happy with everything and want me to merge this!

**Comment by fonsp** [comment]
> include the entire vega and vega-lite codebase again and again

Pluto deduplicates scripts that occur multiple times to solve this ✔️

**Comment by fonsp** [comment]
Can we go back to loading the scripts from CDNs? And to fixing the CDN versions in a separate variable?

**Comment by fonsp** [comment]
> use the sourceMap-less artifacts with the full html as well? (prevents a console warning)

Don't worry about that, because we are not debugging the JS source code of vegalite itself

**Comment by mcmcgrath13** [comment]
I'll switch to the CDN version, but I'll lift the versions from the vega lite artifact so they're consistent with the package.  The warning on source map just shows up in the inspector - it's not a big deal as we're not debugging the js there, I just found it annoying.

**Comment by mcmcgrath13** [comment]
Updated with the CDN usage.  I think this is good to go @davidanthoff (I'll make the same changes over on Vega.jl shortly)

**Comment by mcmcgrath13** [comment]
[Vega PR](https://github.com/queryverse/Vega.jl/pull/33)

**Review by fonsp — APPROVED** [review]
Awesome, thanks for your patience! Did you run this in Pluto to make sure that it now works?

**Comment by mcmcgrath13** [comment]
> Awesome, thanks for your patience! Did you run this in Pluto to make sure that it now works?

Yup! Tooltips and dropdowns and other js-ey things work like a charm!

**Comment by davidanthoff** [comment]
Fantastic, much appreciated!

**Comment by diegozea** [comment]
Thanks for this work! :D It would be awesome to have this tagged :)

**Comment by fonsp** [comment]
Thanks @davidanthoff !

**Pull request merged**
