### PR TITLE
Reduced time it takes to save VL to non-SVG outputs

### PR DESCRIPTION
**Pull request by rben01**
Finally fixed the git snafus 😄. This commit has exactly the diff that fixes the long save times, as demonstrated below using the problematic code from #331.

# Before

```julia
(@v1.7) pkg> status VegaLite
      Status `~/.julia/environments/v1.7/Project.toml`
  [112f6efa] VegaLite v2.6.0

julia> using VegaLite

julia> x = 1:40000; y = sin.(x/1000);

julia> v = @vlplot(:line, x = x, y = y)

julia> @time save("test_vegalite.png", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/b8swT/src/ImageMagick.jl:180
 58.086279 seconds (9.97 M allocations: 461.655 MiB, 0.91% gc time, 2.42% compilation time)

julia> @time save("test_vegalite.pdf", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/b8swT/src/ImageMagick.jl:180
 55.264930 seconds (4.63 M allocations: 129.824 MiB, 0.06% gc time, 0.06% compilation time)
```

# After

```Julia
(@v1.7) pkg> status VegaLite
      Status `~/.julia/environments/v1.7/Project.toml`
  [112f6efa] VegaLite v2.6.1-DEV `~/Downloads/VegaLite.jl`

julia> using VegaLite

julia> x = 1:40000; y = sin.(x/1000);

julia> v = @vlplot(:line, x = x, y = y)

julia> @time save("test_vegalite.png", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/b8swT/src/ImageMagick.jl:180
  1.006354 seconds (281.25 k allocations: 25.764 MiB, 3.82% gc time)

julia> @time save("test_vegalite.pdf", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/b8swT/src/ImageMagick.jl:180
  1.027480 seconds (280.87 k allocations: 26.173 MiB)
```

(Not sure what's going on with those ImageMagick warnings, but that's for another investigation.)

### CODE REVIEW

**Comment by rben01** [comment]
Just following up on this.

**Comment by rben01** [comment]
No luck. After one round of running to get everything precompiled, we have:

Upstream
```Julia
(julia-test) pkg> status VegaLite
Status `~/Downloads/julia-test/Project.toml`
  [112f6efa] VegaLite v3.2.1-DEV `https://github.com/queryverse/VegaLite.jl#master`

julia> @time save("test_vegalite.png", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/ImageMagick.jl:179
 53.353215 seconds (3.17 M allocations: 104.949 MiB, 0.10% gc time)

julia> @time save("test_vegalite.pdf", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/ImageMagick.jl:179
 50.497843 seconds (3.17 M allocations: 105.354 MiB, 0.03% gc time)
```

My branch
```Julia
(julia-test) pkg> status VegaLite
Status `~/Downloads/julia-test/Project.toml`
  [112f6efa] VegaLite v2.6.1-DEV `https://github.com/rben01/VegaLite.jl#improve-render-time`

julia> @time save("test_vegalite.png", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/ImageMagick.jl:179
  0.800364 seconds (281.31 k allocations: 25.458 MiB)

julia> @time save("test_vegalite.pdf", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/ImageMagick.jl:179
  0.869478 seconds (280.86 k allocations: 25.863 MiB)
```

(I'm on the same hardware as a year ago, but a different version of macOS and a different version of Julia, so these results should be somewhat comparable to the original ones.)

My rationale behind buffering was that the pipelines are probably (this is just a guess though) using too small a buffer and data is being pulled from one into the other very few bytes at a time. If you buffer everything then that problem goes away.

I will try your suggestion of stripping the data out of the spec and saving it to disk so that it doesn't have to be sent over a pipeline.

**Comment by rben01** [comment]
I've implemented what I think is your idea here: https://github.com/rben01/VegaLite.jl/blob/feb0ff5f74826dd2af76d2b8a4131dffdff9354c/src/rendering/show.jl#LL1C1-L1C1

```Julia
function convert_vl_to_x(v::VLSpec, fileformat; cmd_args="")
    script_path = vegalite_app_path("node_modules", "vega-lite", "bin", "vl2$fileformat")

    data = get(v.params, "data", nothing)
    if data !== nothing
        values = pop!(data, "values", nothing)
        if values !== nothing
            (path, io) = mktemp(; cleanup=false)  # for testing; change this back to `true` eventually
            println(path)
            JSON.print(io, values)
            close(io)
            data["url"] = "file://$path"
            data["format"] = OrderedDict("type" => "json")
        end
    end

    p = open(Cmd(`$(NodeJS_18_jll.node()) $script_path $cmd_args`, dir=vegalite_app_path()),"r+")
    writer = @async begin
        our_json_print(p, v)
        close(p.in)
    end
    reader = @async read(p, String)
    wait(p)
    res = fetch(reader)
    if p.exitcode != 0
        throw(ArgumentError("Invalid spec"))
    end
    return res
end
```

It's an improvement! But not really in the ballpark of my PR.
```Julia
julia> @time save("test_vegalite.png", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/ImageMagick.jl:179
 15.701747 seconds (85.14 k allocations: 5.216 MiB, 0.25% compilation time)

julia> @time save("test_vegalite.pdf", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/ImageMagick.jl:179
 17.100200 seconds (1.39 k allocations: 3.104 MiB)
```

I think that writing *anything* over the pipeline without an intermediate buffer is really slow. I don't know why — maybe JSON itself needs to do some buffering? Maybe it's only writing (say) byte by byte?

**Comment by davidanthoff** [comment]
Could you try https://github.com/queryverse/VegaLite.jl/pull/434 and see how that performs relative to your version? That uses https://github.com/JuliaIO/BufferedStreams.jl, which I think is presumably what we want?

**Comment by rben01** [comment]
Yep, this is the one 🙌. I haven't done any profiling but I assume BufferOutput does something between buffering everything and buffering nothing? Say, buffering and flushing 10kb at a time?

```Julia
(julia-test) pkg> st VegaLite
Status `~/Downloads/julia-test/Project.toml`
  [112f6efa] VegaLite v3.2.1-DEV `https://github.com/queryverse/VegaLite.jl#buffered-output`

julia> @time save("test_vegalite.png", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/ImageMagick.jl:179
  0.832497 seconds (281.39 k allocations: 23.321 MiB)

julia> @time save("test_vegalite.pdf", v)
┌ Warning: Mapping to the storage type failed; perhaps your data had out-of-range values?
│ Try `map(clamp01nan, img)` to clamp values to a valid range.
└ @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/ImageMagick.jl:179
  0.908311 seconds (280.97 k allocations: 23.725 MiB)
```

**Comment by rben01** [comment]
Btw, I don't think you need to flush then close [here](https://github.com/queryverse/VegaLite.jl/blob/5fa53066aa189fd28783490ec3b7ae2b48d9989a/src/rendering/show.jl#L11), as closing already flushes.

```Julia
help?> close
search: close closewrite colorschemes colorscheme! test_colorscheme

  close(stream)


  Close an I/O stream. Performs a flush first.
```

**Comment by davidanthoff** [comment]
> I assume BufferOutput does something between buffering everything and buffering nothing? Say, buffering and flushing 10kb at a time?

Yes, that is my understanding. The default buffer size is 128 KiB, see [here](https://github.com/JuliaIO/BufferedStreams.jl/blob/3a6edac541ff380b38c6da3d578a47de1c17e3b7/src/BufferedStreams.jl#L13). We could probably experiment with that, maybe something larger would work even better? I'm going to merge my PR soon, and if you want to give it a go and see whether a larger buffer size improves performance even more, that would be great!

>  I don't think you need to flush then close

Yep, thanks, fixed!

**Pull request closed without merging**
