### PR TITLE
Faster startup

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Note, -O1 gets you most of the speedup, but -O0 a bit more, and I think it justified here.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Very nice! I think we can try this and see how it goes. Do we need to be a bit worried that some things might be slower with this, or should this just be a universal speedup?

**Comment by PallHaraldsson** [comment]
I'm no expert on your package, but since it's a wrapper package, I'm not worried. There are other tricks available, e.g. to reduce invalidations. Those tricks can be an alternative or I understand used together.

**Comment by davidanthoff** [comment]
There are a few places in the code where we loop over things that can potentially be large, I think. Would one strategy be that we move these into a sub module, and then enable full optimizations for that sub module?

**Comment by PallHaraldsson** [comment]
Possibly, but -O1 is also a middle ground (Plots.jl uses that), and I think it doesn't disable that many optimizations. --compile=min is extreme, and then I would worry more.

If the Plots.jl guess are not worried, I assumed same goes here (while I went one step further). You could always time something, or wait for performance regressions reports...

**Comment by PallHaraldsson** [comment]
If many users are on master, you would wait a bit with tagging a new release. However, do you know how that works, you would only get the latest master if you do "up"?

This might be worth it for some of your dependencies, as -O0 gets one more extra sec. of loading, and then another with:
```
$ ~/julia-1.6.0-rc1/bin/julia -O0 --compile=min -q

julia> @time using VegaLite
  0.904188 seconds (750.00 k allocations: 55.957 MiB)
```

**Pull request merged**
